### PR TITLE
Adding handling of ampersands.

### PR DESCRIPTION
**Pull request by pberger514**
This feature handles ampersands, i.e. references to parent objects, in Objective Matlab files. I've tested it on a pretty large Objective Matlab codebase that I'm porting and it works for all the cases I've encountered there.

I've added a test class so you can see some sample output. From `matlab2python/tests/files` run:

`python ../../matlab2python.py test_class2.m`

The output should be

    from MyClass import MyClass
    
    class ChildClass(MyClass):
    
            
       def __init__(self = None,varargin = None): 
            MyClass.__init__(self,varargin)
            return
            
            
        def parse(self = None,input_ = None): 
            value = self.child_value + input_
            return value
            
            
        def read(o = None,value = None): 
            MyClass.read(o,self.parse(value))
            return

### CODE REVIEW

**Comment by ebranlard** [comment]
Hi @HaMetBacon 

Thanks a lot for doing that, and thanks for adding an example. 

If you find the time, can you try to write a test for your feature? I don't think there is an easy way to test just this feature in a way done in `tests/test_parser.py`.  Instead, you could try to add something in `tests/test_files.py` (which is intended to test the conversion of test files like the one you added). But I'm really sorry that there is not much comment in this test script, and I can see that it's a bit incomplete. 

I believe the function `compare_to_ref` had the ambition of comparing a converted m file to a reference python file (maybe doing simple string comparison), but I never got to that, or dropped the idea. 

You could maybe write something merging the idea between the two `test_spectrum` functions, where you first convert the test_file that you added, then try to import it, run it, and compare the results with the expected one (with a test.assertEqual). You might need to change your example file a bit so that it's runnable. 

I'm happy to discuss more, feel free to do whatever is simpler for you!

**Comment by pberger514** [comment]
Hi @ebranlard,

Sorry for the delayed response, been busy. 

I can definitely set up tests properly but it seems like there are some blocking issues I'm not sure how to handle. Specifically, for the module to import without error, it needs to find `MyClass.py`. So it would first have to convert `test_class1.m` into `MyClass.py`. The order can just be enforced manually in the tests, but it means enforcing a Matlab-like standard that class definition files are named after the class and contain only the class, which could be fine for tests.

**Comment by ebranlard** [comment]
Hi Philippe, 

No worries, thank you for your contribution and getting back. I'm also slow at answering, sorry. 
It's fine by me if we put the file MyClass.py somewhere in the repo, for instance in tests/files/MyClass.py. During the test, we can the directory tests/files/ into the system path, convert the file test_class2.m, import the python version, call the function read and makes sure it returns what's expected. 

If you think you have time to do that, let me know. Otherwise, I'll merge your pull request and mark this as a todo.

**Comment by ebranlard** [comment]
I've actually done a tiny bit of cleanup of the tests. 

I think it shouldn't be too difficult to now add a test for your class based on this one: 
https://github.com/ebranlard/matlab2python/blob/master/tests/test_files.py#L68

If you want you can first convert the parent class `pyFilename = convert('tests/files/test_class1.m' , '')`   (without a prefix). 
Add the directory to the system path :`sys.path.append(os.path.dirname(pyFilename))` 
Then convert and test the import of your `ChildClass`. 

Keep me in touch!

**Comment by pberger514** [comment]
Awesome, thanks for the cleanup.

I've added the new test which also showed there was an important case I wasn't handling in the code. Seems to be working now!

**Comment by ebranlard** [comment]
Thanks a lot for doing that! the testing framework looks pretty useful.

**Pull request merged**
